# Generated by Django 3.0.7 on 2020-06-20 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriUtama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('keterangan', models.TextField(verbose_name='Keterangan')),
            ],
        ),
        migrations.CreateModel(
            name='KategoriTambahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('keterangan', models.TextField()),
                ('kategori_utama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.KategoriUtama')),
            ],
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('foto', models.ImageField(upload_to='news/static/news/image')),
                ('tgl_post', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('kategori_tambahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.KategoriTambahan')),
                ('kategori_utama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.KategoriUtama')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
