# Generated by Django 3.0.8 on 2020-12-10 20:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('headline', models.TextField()),
                ('isi', ckeditor.fields.RichTextField()),
                ('foto', models.ImageField(upload_to=news.models.upload_location)),
                ('tgl_post', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=False)),
                ('tgl_publish', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Berita',
            },
        ),
        migrations.CreateModel(
            name='KategoriUtama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('keterangan', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Kategori utama',
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.TextField()),
                ('tgl_post', models.DateTimeField(auto_now_add=True)),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Berita')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Komentar',
            },
        ),
        migrations.CreateModel(
            name='KategoriTambahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('keterangan', models.TextField()),
                ('kategori_utama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.KategoriUtama')),
            ],
            options={
                'verbose_name_plural': 'Kategori tambahan',
            },
        ),
        migrations.AddField(
            model_name='berita',
            name='kategori_tambahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.KategoriTambahan'),
        ),
        migrations.AddField(
            model_name='berita',
            name='kategori_utama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.KategoriUtama'),
        ),
        migrations.AddField(
            model_name='berita',
            name='penulis',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
