# Generated by Django 3.0.7 on 2020-06-27 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20200624_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'verbose_name_plural': 'Berita'},
        ),
        migrations.AlterModelOptions(
            name='kategoritambahan',
            options={'verbose_name_plural': 'Kategori tambahan'},
        ),
        migrations.AlterModelOptions(
            name='kategoriutama',
            options={'verbose_name_plural': 'Kategori utama'},
        ),
        migrations.AlterModelOptions(
            name='komentar',
            options={'verbose_name_plural': 'Komentar'},
        ),
        migrations.AddField(
            model_name='berita',
            name='publish',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='berita',
            name='penulis',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
