# Generated by Django 3.1.3 on 2020-12-01 15:22

import ckeditor.fields
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200627_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='header',
        ),
        migrations.AlterField(
            model_name='berita',
            name='foto',
            field=models.ImageField(upload_to=news.models.upload_location),
        ),
        migrations.AlterField(
            model_name='berita',
            name='isi',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='berita',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kategoriutama',
            name='keterangan',
            field=models.TextField(),
        ),
    ]
