# Generated by Django 3.1.3 on 2020-12-03 20:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201201_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='kategori_utama',
        ),
        migrations.AddField(
            model_name='berita',
            name='headline',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='berita',
            name='tgl_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 20, 29, 33, 217233)),
            preserve_default=False,
        ),
    ]
