# Generated by Django 3.1.3 on 2020-12-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201203_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='tgl_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
